### ISSUE TITLE
フッターから遷移するサイトポリシーページを作成する

### ISSUE THREAD

**Issue by Nekoya3** [codeforjapan/StudyAtHome#101]
サイトポリシーページを作成する
画面遷移はFigmaを参照してください

![TermsOfService-page _fromFooter](https://user-images.githubusercontent.com/17000370/83971717-e0dad080-a917-11ea-84a0-a39dbe4bd7fc.png)

**Comment by kaizumaki** [comment]
こちらやりますね。 #102 を単純にコピペしてフォーム要素を削除します。
