### ISSUE TITLE
利用規約への同意ページを作成する

### ISSUE THREAD

**Issue by Nekoya3** [codeforjapan/StudyAtHome#102]
画面遷移はFigmaを参照してください
![TermsOfService-page](https://user-images.githubusercontent.com/17000370/83971832-3fa04a00-a918-11ea-8963-de725ffd8dbc.png)

**Comment by kaizumaki** [comment]
ちょっと気になったので、用語の整理をさせてください！
テキスト中に「本プライバシーポリシーに～」と書いてあって、同意のチェックは「サイトポリシー」であることに違和感を感じます。プライバシーポリシーは別途ページがあるのでしょうか？（もしくは上記の画像では見えていないだけ？）

ちなみにこちらを参考にしました。
https://attadesign.co.jp/blog/715/

**Comment by kjinnouchi** [comment]
プライバシーポリシーはCode for Japanのプライバシーポリシーになります。
そのため、こちらへのリンクを想定していると思います。
https://www.code4japan.org/privacy-policy
また、私も「サイトポリシー」の同意ボタンは違和感があります。

**Comment by Nekoya3** [comment]
![TermsOfService-page (1)](https://user-images.githubusercontent.com/17000370/84104262-226e9700-aa50-11ea-9364-be441993dc47.png)
ボタンの上下を逆にし、チェックボックスの文言を「利用規約に同意します」に変更しました！
文章については変更する可能性が高いため、いったん画像の文章を入れていただき、後ほど文章のみ変更させていただきます！

**Comment by kaizumaki** [comment]
@Nekoya3 了解しました！ではこちらのissueは引き受けますね。

**Comment by Nekoya3** [comment]
@kaizumaki よろしくお願いします！
