### ISSUE TITLE
閲覧者（学生側）のページを作成する

### ISSUE THREAD

**Issue by Nekoya3** [codeforjapan/StudyAtHome#103]
画面遷移はFigmaを参照してください
![viewer-page](https://user-images.githubusercontent.com/17000370/83971929-9c9c0000-a918-11ea-8821-cdfff9be7331.png)

**Comment by kaizumaki** [comment]
こちらのissueやります。
ルーティングのpath名は何か指定がありますか？

**Comment by Nekoya3** [comment]
現在/classesを割り当ててますが、他に良い名前があればそちらでもOKです

**Comment by kaizumaki** [comment]
@Nekoya3 了解です！ `src/pages/classes/index.vue` に手を入れる感じですね。 ということはすでにほとんどできていますね。
