### ISSUE TITLE
v-overlayの表示切替をvalue属性にする

### ISSUE THREAD

**Issue by kaizumaki** [codeforjapan/StudyAtHome#111]
## 改善詳細 / Details of Improvement
- `v-overlay` の表示切替が `v-if` になっていますが、[Vuetifyのドキュメント](https://vuetifyjs.com/ja/components/overlays/)を見ると、`value` のほうが正しいと思われます。

## 期待する見せ方・挙動 / Expected behavior
- `v-overlay` の表示切替を `:value` にする。
- オーバーレイの挙動は変えない。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by Nekoya3** [comment]
確かにですね...

**Comment by Nekoya3** [comment]
同時に色設定もscssの変数が正しく読めていないようなので修正いただけるとと...

**Comment by kaizumaki** [comment]
@Nekoya3 私やりますよ！

**Comment by Nekoya3** [comment]
@kaizumaki ありがとうございます！
(東京版から流用したコードなので東京版の修正issueなど立てておきますー）
