### ISSUE TITLE
授業の編集、追加画面の実装

### ISSUE THREAD

**Issue by Nekoya3** [codeforjapan/StudyAtHome#117]
https://www.figma.com/file/JBcf0nDLMqOyS5vffbZtvw/covid-edu?node-id=894%3A2821
画面遷移、各ボタンなどの挙動はこちらを参照してください

![owner-page-1](https://user-images.githubusercontent.com/17000370/84236234-4e624900-ab32-11ea-8f08-504d10086b36.png)
![owner-page-2-0](https://user-images.githubusercontent.com/17000370/84236249-5326fd00-ab32-11ea-8165-4a3cb19f7d9c.png)
![owner-page-2-1](https://user-images.githubusercontent.com/17000370/84236250-5326fd00-ab32-11ea-8613-16bf61202209.png)
![owner-page-2-2](https://user-images.githubusercontent.com/17000370/84236245-528e6680-ab32-11ea-90fe-e3ada5808c01.png)
![owner-page-2-3](https://user-images.githubusercontent.com/17000370/84236246-528e6680-ab32-11ea-935f-bec418c0a4d7.png)

**Comment by kaizumaki** [comment]
こちらのissueやりますね。
ざっと見て１点気づいたのですが、１ページ目のヘッダーと２ページ目以降のヘッダーが異なっているのですが、これはこのまま実装でしょうか？

↓１ページ目のヘッダー
![1ページ目](https://user-images.githubusercontent.com/14883063/84237554-81a5d780-ab34-11ea-8e3d-763f05946ad1.jpg)

↓２ページ目以降のヘッダー
![2ページ目以降](https://user-images.githubusercontent.com/14883063/84237569-8d919980-ab34-11ea-84ce-41727c891385.jpg)

**Comment by Nekoya3** [comment]
2ページ目以降のものにそろえていただいてもいいでしょうか？
1枚目の画像の下部にあるフッターは #69 で作成されていて、黄色い+ボタンと白いペンのボタンを押すと下からにゅーっと出てくる感じになります...
また、カレンダーのボタンを押すとv-date-pickerが、時計のボタンを押すとOSに応じた時間のピッカーが、パレットのボタンを押すとv-color-pickerが表示される感じになります。（いったんそこのモーダルは放置でも大丈夫です）

**Comment by kaizumaki** [comment]
もうひとつわからないところがあるのですが、「動画サムネイル・キャプション表示」というのは、上の「参考動画URL」に入力すると自動で表示されるエリアなんでしょうか...？

![動画サムネイル表示](https://user-images.githubusercontent.com/14883063/84340350-7c4f9800-abdb-11ea-8dba-bdc876efdd14.jpg)

**Comment by forestgtree** [comment]
URL入力後、エンターもしくは右のリンクボタンを押すとサムネイル画像とキャプション表示が良いのではないか？と思いデザインしました。

他の入力欄は、入力フォームの右側ボタンがピッカー起動になるので文法が異なりユーザーが迷うところだと思います。
なので、明示的にピッカー起動のボタンが主の場合は、入力フォームを透明にする事で、何をすべきかのヒントになるのではないかと…

それと、URLの入力欄には「URLを入力して下さい」と表記すべきですね。
デザイン上は既にURLが入力された後の絵になります。

**Comment by F88** [comment]
過去の検討の中では、OGPなりで取れる情報があればそれを利用し、別途事前に用意された候補の動画関連データがあり、そこには予めサムネイルも用意されているような場合はそれを表示するような話もありました。前者は例えばYoutubeの動画、後者はシステムとして予め用意してあるデータセットのようなイメージでしょうか。動画の設定については未だUI含め要検討な点が残っているという認識です。

**Comment by kaizumaki** [comment]
@forestgtree 回答ありがとうございます！フィールドの見た目のすみ分け、理解しました。編集画面用にinputのコンポーネントを分けようと思います。

@F88 状況把握しました。この機能については別issueに切り出しますね。
