### ISSUE TITLE
ログイン後のクラスのセレクタ画面の作成

### ISSUE THREAD

**Issue by Nekoya3** [codeforjapan/StudyAtHome#122]
ログイン後に先生がクラスを選択するための画面です。
Vuetifyコンポーネントを利用いただけると助かりますが、どちらでも構いません。
ページルーティングはお任せします。
![ClassList-page-1](https://user-images.githubusercontent.com/17000370/84246988-6346d880-ab42-11ea-8f33-d0a769c65830.png)

**Comment by kaizumaki** [comment]
こちらのissueやりますね。 `v-bottom-sheet` を使う感じでしょうか？

**Comment by Nekoya3** [comment]
v-bottom-sheetにfullscreenを当ててあげるのが一番楽かもしれませんが....ページとして遷移するため、別なアプローチでもOKです！
可能であればログインする、クラスを登録するの部分はページ下部に固定してもらいたいです....（画面表示以上になるとリストの部分のみスクロールする感じです）

**Comment by kaizumaki** [comment]
@Nekoya3 了解です！ルーティングを設定するのが前提ですね。
