### ISSUE TITLE
クラスの登録画面の作成

### ISSUE THREAD

**Issue by Nekoya3** [codeforjapan/StudyAtHome#124]
![SignUp-page-2](https://user-images.githubusercontent.com/17000370/84250095-925f4900-ab46-11ea-93c1-285a0591a5c3.png)
![SignUp-page-end](https://user-images.githubusercontent.com/17000370/84250100-94290c80-ab46-11ea-8015-ecaec12c594c.png)

クラス登録画面を作成して下さい！
signup後初めてのクラス作成の場合とそれ以降の作成の場合でヘッダーの表示内容に変更がありますが、現在文言が確定していないため同一で構いません

**Comment by kaizumaki** [comment]
こちらのissueやりますね。この２つは別々のルーティングということでいいですか？

**Comment by Nekoya3** [comment]
クラスを登録した際にしか利用しないので、どちらでもOKです...（別々のほうが楽でしょうか？)

**Comment by kaizumaki** [comment]
@Nekoya3 うーん、フローがいまいちわかっていないのでなんとも言えないですが...
とりあえず別々のpageで作っておきますね（そのほうが早そう）。
