### ISSUE TITLE
aboutページを作成する

### ISSUE THREAD

**Issue by Nekoya3** [codeforjapan/StudyAtHome#14]
## 改善詳細 / Details of Improvement
- このページがどういうページなのかを伝えるaboutページを作成する

**Comment by mamisada** [comment]
https://StudyAtHome.code4japan.org/(暫定案)で、LP制作

- top(アイキャッチ)
- news(更新情報)
- about(概要説明)
- product(サービス・使い方案内)
- project(今後の予定・参加方法)
- contributers(協力・協賛・参加者)
- FAQ/contact(問合せ)

**Comment by mamisada** [comment]
@Nekoya3 Code4のサブドメインで、「https://StudyAtHome.code4japan.org/」で大丈夫ですか？

**Comment by yokinist** [comment]
## 前提
- サイトについて伝わるページを23までに出したい(ミニマムでもいいので)

## 進め方のイメージ
> (5/17現在)

- `FigmaでLPデザインつくる` -> `共有` -> `Studioで制作 or コーディング`  -> `~ 5/23 リリース`

という感じですかね、、

改めて大杉くんから共有あるかと思いますが取り急ぎメモとして残しておきます！いまのところはリリースが早そうなStudioが可能性高そう。だがミニマム具合によってはコーディングした方が早いケースもありえそう。共有するタイミングでの開発リソースやスケジュールを踏まえ、再度どっちでいくかについては決めるのがいいかなと。

### 備考
```
Studioで制作する: リリースまでが早いが、切り離される
デザインデータまでつくって渡す: デザインできるまでは早いが、コーディングする必要がある
```

**Comment by Nekoya3** [comment]
aboutページを用意する方向で調整中

**Comment by MaySoMusician** [comment]
旧仕様に基づいていたissueであるためoutdatedと判断
