### ISSUE TITLE
生徒側の詳細画面、先生側のプレビュー画面を作成する

### ISSUE THREAD

**Issue by Nekoya3** [codeforjapan/StudyAtHome#140]
![preview-page](https://user-images.githubusercontent.com/17000370/84502266-fde61980-acf2-11ea-9863-439e3bd1f679.png)

**Comment by F88** [comment]
実装します :)

**Comment by F88** [comment]
最初の括弧は半角、後のものがいわゆる全角括弧なのですが、後者の方で実装します。(Noto Sans JP)

![image](https://user-images.githubusercontent.com/685250/84569853-6a7d1900-adc4-11ea-85e2-14656327f908.png)

**Comment by F88** [comment]
上の出力が現時点での src/components/VideoThumbnail.vue 、下の出力がデザインに合わせて実装したもの。VideoThumbnail を利用するところは現時点で編集時とこの画面のみではあるが、他にも利用する機会が増えたら考えた方が良いかも。YouTube等の再生を考慮すると共通で利用出来ると良いとは思う。
今回はとりあえず個別実装で。(既にVideoThumbnail は編集画面で利用している為)

![image](https://user-images.githubusercontent.com/685250/84573278-88557880-adda-11ea-83ff-30b4e6c6f3ad.png)

**Comment by F88** [comment]
tipの動画アイコンは遷移元画面と同じものを利用

![image](https://user-images.githubusercontent.com/685250/84573973-b341cb80-adde-11ea-9b10-83030281d554.png)

**Comment by F88** [comment]
最新の型定義に対応しました classData.LessonWithId

**Comment by F88** [comment]
画面としては基本的には動作するのでこの後PRを用意します。

- 詳細画面は /pages/lesson/index.vue として用意しました
- 一覧画面などのカードに対するイベントをトリガーにし `lessonId`の値にLessonIdを付けて /lessons/ にルーティングします

**Comment by F88** [comment]
#161 にて development ブランチにマージ済みなのでcloseしておきます.
