### ISSUE TITLE
ClassDataStore.lessonsOnCurrentDate()で取得出来ないデータがあり得る

### ISSUE THREAD

**Issue by F88** [codeforjapan/StudyAtHome#146]
## 起こっている問題 / The Problem

運用上はあり得ないと思いますが、取得対象に 23:59:59.001 ~ 24:59:59.999 のデータが含まれません。

https://github.com/codeforjapan/StudyAtHome/blob/development/src/store/modules/classData.ts#L22-L40

## スクリーンショット / Screenshot

n/a

## 期待する見せ方・挙動 / Expected Behavior

- 任意の日付に含まれるべきデータを取得する

## 起こっている問題の再現手段 / Steps to Reproduce

再現するのは困難です

## 動作環境・ブラウザ / Environment

n/a

## 修正案

```diff
diff --git a/src/store/modules/classData.ts b/src/store/modules/classData.ts
index c3c8f02..da5f6fc 100644
--- a/src/store/modules/classData.ts
+++ b/src/store/modules/classData.ts
@@ -4,6 +4,7 @@ import {
   action,
   createProxy
 } from 'vuex-class-component'
+import add from 'date-fns/add'
 import firebase from '@/plugins/firebase'
 import { AppStore } from '@/store/modules/app'
 import Timestamp = firebase.firestore.Timestamp
@@ -52,19 +53,28 @@ export class ClassDataStore extends VuexModule implements ClassData {
     const appStore = createProxy(this.$store, AppStore)

     // Generate a new Date object with a specified date & time
-    const d = (date: Date, hours: number, minutes: number, seconds: number) => {
+    const d = (
+      date: Date,
+      hours: number = 0,
+      minutes: number = 0,
+      seconds: number = 0,
+      milliseconds: number = 0
+    ) => {
       const newDate = new Date(date)
       newDate.setHours(hours)
       newDate.setMinutes(minutes)
       newDate.setSeconds(seconds)
+      newDate.setMilliseconds(milliseconds)
       return newDate
     }
-    const start = d(appStore.currentDate, 0, 0, 0).getTime()
-    const end = d(appStore.currentDate, 23, 59, 59).getTime()
+    const start = d(appStore.currentDate, 0, 0, 0)

     return this.lessons.filter(lesson => {
       const startOfLesson = lesson.startTime.getTime()
-      return start <= startOfLesson && end >= startOfLesson
+      return (
+        start.getTime() <= startOfLesson &&
+        startOfLesson < add(start, { days: 1 }).getTime()
+      )
     })
   }
```

**Comment by F88** [comment]
本件ですが、 #140 の実装中に気付いたものです、修正案通りで問題無ければ #140 対応に含めてPR用意しようと思います。

**Comment by F88** [comment]
再現と修正後の確認のためのテストケースを書いたのですが、テスト実行時にfirebase関連のimportが上手く行かない問題が発生し解消出来なかったので再現テストが用意出来ていません、悪しからず。

**Comment by MaySoMusician** [comment]
最終的に `start` 変数だけになるなら、直接 new Date(...) に戻してしまって良いと思います！
（ `appStore.currentDate` の `getFullYear()` とかを2回書きたくなかったためだけに用意したラッパー関数なので）

**Comment by F88** [comment]
なるほど、そういう事情もあったんですね

**Comment by Nekoya3** [comment]
23:59:59.001 ~ 24:59:59.999ではなく、23:59:59.000000001 ~ 23:59:59.999999999かと思いますが、入力欄に秒を入力するフィールドがない関係で、秒以下の数値はほぼ存在しない(あってもなくても変わんない）という風な考えでいいかと思っています。まず、それを指定する手段がコード側から**無理やりnanosec、millisecを設定しない限り存在しない**はずなのですが...

**Comment by F88** [comment]
そうですね、とりあえず汎用的にしようかと思ったのがこのIssueなのですが、後から考えるとミリ秒を入力するUIは無いですし、その通りなのです。潜在的なバグになると良くないので条件反射的にIssue立てましたが、実運用上は問題無く動作すると思います。とりあえず対応無しでcloseしましょうか。特に問題無いです。

> ㎱
https://firebase.google.com/docs/reference/js/firebase.firestore.Timestamp#todate
の通り現実装上だとナノ秒は捨てられるようです。

**Comment by F88** [comment]
`won't fix` 扱いでcloseしましょ
