### ISSUE TITLE
PeriodCard と PeriodCardEditable の統合

### ISSUE THREAD

**Issue by MaySoMusician** [codeforjapan/StudyAtHome#153]
何故か ContentCard と ContentCardEditable が統合されてしまったが（https://github.com/codeforjapan/StudyAtHome/pull/139/commits/e1179b3a1958aba1af525ab8b52555b90dac8053 / 統合して問題ないのならそれは良いこと）、現状としてはPeriodCard と PeriodCardEditableの方が類似度が高い（感覚的な検証）

今の実装の様子だと、Edit処理はイベントをemitしていって親コンポーネントに書くので、PeriodCardEditableに処理そのものを書くことは無さそうなので、統合しても問題ないかと思われる

**Comment by F88** [comment]
これ見てみようかと思ったのですが、対象が #160 にて対応中なので、そちらがfixするまでとりあえず待ちます.
