### ISSUE TITLE
N時間目の表示を正常にする

### ISSUE THREAD

**Issue by Nekoya3** [codeforjapan/StudyAtHome#160]
現在、すべて1時間目00*00 - 00:00と書いているものをstartTimeごとにグルーピングしたいです。
endTimeが異なっていても、startTimeが同じであれば同じN時間目にグループ化してもらい、00:00-00:00の部分はstartTime-endTime（複数ある可能性がありますが、どれか1つが表示される）にしていただきたいです。
![image](https://user-images.githubusercontent.com/17000370/84586840-9e544f00-ae55-11ea-88a3-cc883d3633f5.png)

↓

![image](https://user-images.githubusercontent.com/17000370/84586904-0145e600-ae56-11ea-9655-35ffd60faccd.png)

**Comment by kaizumaki** [comment]
こちらのissueやりますね。
