### ISSUE TITLE
各components, stores, firebaseの結合度を下げる

### ISSUE THREAD

**Issue by MaySoMusician** [codeforjapan/StudyAtHome#190]
それぞれpropsや [https://www.npmjs.com/package/provide-consume-decorator](provide-consume-decorator) などを利用する。
テストや他のAPIへの乗り換えを容易にする

参考URL: https://dev.to/nesterow/testable-code-with-vuejs-and-typescript-4eeb

**Comment by MaySoMusician** [comment]
こちら、Social Hack Day 16 で取り組もうと思います

**Comment by Nekoya3** [comment]
GraphQLに移行のためCLose
