### ISSUE TITLE
クラス追加後、意図的に再ログインしない限りクラス選択画面に追加したクラスが表示されない

### ISSUE THREAD

**Issue by F88** [codeforjapan/StudyAtHome#198]
## 起こっている問題 / The Problem

- (#197 が解消された後)
- クラス追加後、意図的に再ログインしない限りクラス選択画面に追加したクラスが表示されない

## スクリーンショット / Screenshot

- n/a

## 期待する見せ方・挙動 / Expected Behavior

- クラス選択画面のクラス一覧に直前に追加したクラスを含む選択可能なクラスが列挙されること

## 起こっている問題の再現手段 / Steps to Reproduce
1. (#197 が解消されていること)
2. 任意のクラスを追加
3. クラス選択操作

## 動作環境・ブラウザ / Environment

- 環境依存性無し

**Comment by F88** [comment]
クラス一覧が表示されるようにしました

**Comment by Nekoya3** [comment]
AWS migrationによってResolved
