### ISSUE TITLE
非表示ボタンが動作しない

### ISSUE THREAD

**Issue by kota-yata** [codeforjapan/StudyAtHome#219]
## 起こっている問題 / The Problem
- 時間割を非表示にするボタンが動作しない

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/51294895/85915014-bfb63180-b87e-11ea-88dc-32a52a6c678d.png)

## 期待する見せ方・挙動 / Expected Behavior
- ボタンを押したら該当する時間割が非表示になる(?)

## 起こっている問題の再現手段 / Steps to Reproduce
1. ログインする
2. 時間割カードの横にある目のボタンを押す

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by soutaito** [comment]
私できるだけやります。
