### ISSUE TITLE
パスワード変更でエラーが出る

### ISSUE THREAD

**Issue by kota-yata** [codeforjapan/StudyAtHome#220]
## 起こっている問題 / The Problem
- パスワードを変更して保存を押すと404エラーが出る
- Firebaseのエラーっぽい

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/51294895/85915183-57684f80-b880-11ea-815e-1a5bccfccc0c.png)
![image](https://user-images.githubusercontent.com/51294895/85915190-5e8f5d80-b880-11ea-9f92-9e38400714aa.png)

## 期待する見せ方・挙動 / Expected Behavior
- 保存を押すと時間割ページに戻り、パスワードは変更される

## 起こっている問題の再現手段 / Steps to Reproduce
1. ログインする
2. 右上の設定ボタンを押す
3. 新しいパスワードを入力して保存を押す

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by Nekoya3** [comment]
#427で解消予定
