### ISSUE TITLE
詳細説明を改行しないとwidthが無限に広がる

### ISSUE THREAD

**Issue by kota-yata** [codeforjapan/StudyAtHome#221]
## 起こっている問題 / The Problem
- 時間割の詳細説明を改行なしで長く書くと無限にWidthが広がり、横スクロールできてしまう
- PCの場合は文字のみはみ出してスクロールはできない

## スクリーンショット / Screenshot
モバイル : 
![image](https://user-images.githubusercontent.com/51294895/85915766-3a824b00-b885-11ea-8336-849068bd035f.png)

PC : 
![image](https://user-images.githubusercontent.com/51294895/85915880-4e7a7c80-b886-11ea-95cc-984b919b34b2.png)

## 期待する見せ方・挙動 / Expected Behavior
- 100vw以内でwidthを固定して強制的に改行する (モバイル)

## 起こっている問題の再現手段 / Steps to Reproduce
1. ログインする
2. 詳細説明を長く書いて時間割を追加する

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by MaySoMusician** [comment]
```css
word-break: break-all;
```
を適宜適用すれば良いと思われる

**Comment by kaizumaki** [comment]
日本語（全角文字）であれば自然に改行されると思われます。念のため `word-break: break-all;` を入れておきますね。
