### ISSUE TITLE
授業編集（≠登録）時に日付・時刻の表示形式を整える

### ISSUE THREAD

**Issue by MaySoMusician** [codeforjapan/StudyAtHome#222]
## 起こっている問題 / The Problem
- 授業の編集画面で、登録済みの授業を編集すると
- 「2020-6-3」「12:0」というような表記になる
- 「2020-06-03」「12:00」にしたり「2020年6月3日」「12時00分」というように日本語化したりした方が良いのではないか？

## スクリーンショット / Screenshot
![](https://drive.google.com/uc?export=view&id=1GiRExCBrZzDAWcc9fo9QLjK_UbGZeuWC)

## 動作環境・ブラウザ / Environment
- Win10 Chrome

**Comment by kaizumaki** [comment]
こちら対応します。
