### ISSUE TITLE
「クラスを登録してください」の文字にCSSを適用する

### ISSUE THREAD

**Issue by MaySoMusician** [codeforjapan/StudyAtHome#223]
## 起こっている問題 / The Problem
- ユーザー登録直後、クラスを始めて追加するときに、「編集可能なクラスがありません。クラスの登録を行なってください。」の文字が黒色で表示される。

## スクリーンショット / Screenshot
- 現在の表示
    ![](https://drive.google.com/uc?export=view&id=1WWu8Wx8QqDjWRKhmEvvfGCqsQn99-rkz)
- 理想の表示
    ![](https://drive.google.com/uc?export=view&id=175dO_d5Vd2qXr4DXgo4IAcuUccRPrC3x)

## 期待する見せ方・挙動 / Expected Behavior
- 白色で、画面中央に表示する

## 動作環境・ブラウザ / Environment
- iPhone8 Safari

**Comment by kota-yata** [comment]
着手します

**Comment by kota-yata** [comment]
このバグを再現するために別アドレスでログインを試みたところ #226 が発生
