### ISSUE TITLE
アカウントのパスワードが「弱い」ときに登録ができない

### ISSUE THREAD

**Issue by MaySoMusician** [codeforjapan/StudyAtHome#227]
## 起こっている問題 / The Problem
- firebaseでは、弱いパスワードでアカウントを登録することができない
- どのようなパスワードなら許容されるのか（何文字以上、大文字小文字含む、など）を明記する
  - 許容されないパスワードが入力されている時は「登録」ボタンが押せない
- 登録エラーのメッセージを専用のものにする
  - 何らかの理由で弱いパスワードで「登録」ボタンが押せてしまったときに、パスワードの強度が登録できない理由であることがわかるエラーメッセージを表示する

**Comment by kota-yata** [comment]
やります
