### ISSUE TITLE
統合issue: TypeScriptに変更する

### ISSUE THREAD

**Issue by Nekoya3** [codeforjapan/StudyAtHome#27]
## 改善詳細 / Details of Improvement
- JavaScriptからTypeScriptに変更する

**Comment by Nekoya3** [comment]
ts対応してくれる方へ
面倒かもしれませんが、各ファイルごとにチケット切ってアサインしていただけるとかぶらないので助かります！

**Comment by Nekoya3** [comment]
原則的にVue.extendを用いてTypeScriptに対応することを

**Comment by MaySoMusician** [comment]
FYI: https://tech.smartcamp.co.jp/entry/try-vue-composition-api

**Comment by Nekoya3** [comment]
PRの先はTypeScript-developmentにお願いします。

**Comment by Nekoya3** [comment]
対応完了
