### ISSUE TITLE
Store/以下のTypeScript対応

### ISSUE THREAD

**Issue by Nekoya3** [codeforjapan/StudyAtHome#30]
統合issue: #27
## 改善詳細 / Details of Improvement
- /store/*のTypeScript対応

**Comment by y-chan** [comment]
多分恐らく高確率でやります

**Comment by MaySoMusician** [comment]
`viewDate` をstring型で持つのをやめよう

**Comment by Nekoya3** [comment]
現状のデータベースに保存されてるデータ
ClassData
`
{
  Lessons: {
     2020-04-20: [
        {
            Content: 'てすと',
            Subject: '国語'
            RealTime: '9:00 - 10:40'
         },
        {
            Content: 'てすと',
            Subject: '数学'
            RealTime: '10:50 - 11:20'
         }
      ]
  },
  className: '2年3組',
   schoolName: 'あさひかわ小学校'
}
`
UserData
`
allow_access: ['くらすこーど','くらすこーで']
`

**Comment by MaySoMusician** [comment]
```json
{ Lessons: { "2020-04-20": [ { Content: 'てすと', Subject: '国語', RealTime: '9:00 - 10:40' }, { Content: 'てすと', Subject: '数学', RealTime: '10:50 - 11:20' } ] }, className: '2年3組', schoolName: 'あさひかわ小学校' }
``

**Comment by MaySoMusician** [comment]
`RealTime` を `startTime` と `endTime` に分ける（時刻系の型にする）

**Comment by Nekoya3** [comment]
https://hackmd.io/@-6Y5YRBcS2aaE4g4aJ17Cw/SkGfvX2cL/edit

**Comment by Nekoya3** [comment]
#47 にて対応終了
