### ISSUE TITLE
時間割の更新でエラーが出る場合がある

### ISSUE THREAD

**Issue by MasaGon** [codeforjapan/StudyAtHome#344]
## 起こっている問題 / The Problem

- 時間割の更新でエラーが出る場合があります
- Networkタブで見ていると何も通信していないようです

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/3581778/91038522-de019900-e645-11ea-88e2-dffba291e9c3.png)

## 期待する見せ方・挙動 / Expected Behavior

- 時間割の更新でエラーが出ないようにする

## 起こっている問題の再現手段 / Steps to Reproduce

1. devサイト および development ブランチのHEAD

## 動作環境・ブラウザ / Environment

- Windows 10
- Chrome

**Comment by Nekoya3** [comment]
解消されていることを確認しました。
