### ISSUE TITLE
ログイン済ユーザーの場合のトップページの動線変更

### ISSUE THREAD

**Issue by MasaGon** [codeforjapan/StudyAtHome#371]
## 改善詳細 / Details of Improvement

- ログイン済みユーザーの場合のトップページの要素を変更したい

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/3581778/93330769-42d19d00-f85a-11ea-9610-887b59a352e3.png)

## 期待する見せ方・挙動 / Expected behavior

- 上記スクショの通り

**Comment by kaizumaki** [comment]
こちら対応します。

**Comment by Nekoya3** [comment]
resolved by #392
