### ISSUE TITLE
タイトルと教科名の入力部分の入れ替え（機能変更なし）

### ISSUE THREAD

**Issue by Nekoya3** [codeforjapan/StudyAtHome#387]
## 改善詳細 / Details of Improvement

- xxxx(できるだけ簡潔に/as concise as possible)

## 期待する見せ方・挙動 / Expected behavior

- xxxx(できるだけ簡潔に/as concise as possible)

## 動作環境・ブラウザ / Environment

- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by mamisada** [comment]
![title](https://user-images.githubusercontent.com/2863745/93996482-45d60b80-fdcd-11ea-9f94-8214d842729a.png)
