### ISSUE TITLE
nuxt-firebaseに変更

### ISSUE THREAD

**Issue by Nekoya3** [codeforjapan/StudyAtHome#40]
## 改善詳細 / Details of Improvement
- xxxx(できるだけ簡潔に/as concise as possible)

## 期待する見せ方・挙動 / Expected behavior
- xxxx(できるだけ簡潔に/as concise as possible)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by MaySoMusician** [comment]
#43 で導入し #49 でリバート
リバート理由は https://github.com/codeforjapan/StudyAtHome/pull/49#issuecomment-629932000 を参照
