### ISSUE TITLE
ユーザー情報変更ページのUI改善（変更項目をわかりやすく）

### ISSUE THREAD

**Issue by kaizumaki** [codeforjapan/StudyAtHome#427]
## 改善詳細 / Details of Improvement
- 現在のユーザー情報変更ページでは「お名前（表示名）」「メールアドレス」「パスワード」のinputがまとめて入っています。
- 実際は、これら３つの変更処理は別々であり、同時に複数の項目の変更に対応していません。
- 特に「パスワード」については「現在のパスワード」を入力する必要があり、現在のUIだとわかりにくくなってしまっています。
- これら３つの項目が別々に変更することがわかるようなUIを検討したいと思います。

## スクリーンショット / Screenshot
↓現在のユーザー情報変更の画面

![スクリーンショット 2020-09-29 15 06 24](https://user-images.githubusercontent.com/14883063/94758071-221b5280-03d7-11eb-9004-d7ba6e95c07d.png)

## 期待する見せ方・挙動 / Expected behavior
- 前段にユーザー情報を確認するページを設けて、その先に３つの項目それぞれの変更ページへ遷移するのが自然かもしれません。
- アイディア募集中！

## 動作環境・ブラウザ / Environment

- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by forestgtree** [comment]
Figmaでデザイン調整してみましたので、確認ください🙇‍♂️
問題なかったら実装お願いいたします！！！

**ユーザー情報変更項目選択画面**

https://www.figma.com/file/XFXhMpD7gVxdpyJeEl4srT/covid-edu?node-id=1480%3A8799

![user-setting-0](https://user-images.githubusercontent.com/55567929/94987228-986ab100-059f-11eb-9e2f-eed2b8e49ed8.png)

**お名前（表示名）変更画面**

https://www.figma.com/file/XFXhMpD7gVxdpyJeEl4srT/covid-edu?node-id=1480%3A9063

![user-setting-1](https://user-images.githubusercontent.com/55567929/94987103-abc94c80-059e-11eb-9d0e-b0ff359b5b10.png)

**メールアドレス変更画面**

https://www.figma.com/file/XFXhMpD7gVxdpyJeEl4srT/covid-edu?node-id=1517%3A0

![user-setting-2](https://user-images.githubusercontent.com/55567929/94987108-b1269700-059e-11eb-8edf-e2b858ddccb0.png)

**パスワード変更画面**

https://www.figma.com/file/XFXhMpD7gVxdpyJeEl4srT/covid-edu?node-id=1518%3A0

![user-setting-3](https://user-images.githubusercontent.com/55567929/94987112-b84da500-059e-11eb-9141-edda8462c3f8.png)

**Comment by kaizumaki** [comment]
デザインありがとうございます！こちらで実装しますね。
「変更する」ボタンを押した後の遷移先としては、「ユーザー情報の変更」ページに戻ってくるのが自然かと思うんですが、いかがでしょう？
以下のような感じです。
- お名前（表示名）の変更→「変更ボタン」を押す→「ユーザー情報の変更」ページ
- メールアドレスの変更→「変更ボタン」を押す→verifyページ→「ユーザー情報の変更」ページ
- パスワードの変更→「変更ボタン」を押す→「ユーザー情報の変更」ページ

**Comment by kaizumaki** [comment]
「メールアドレスの変更」画面の「メールアドレス（確認用）」のフィールドは不要だと思われるので、除外しておきますね。（確認する必要がない・メールアドレスが間違っていたらverifyコードが届かない）

**Comment by MasaGon** [comment]
メールアドレスの重複入力っていうのは、議論が分かれるところですが、僕もあまり意味が無いと思っております。

【参考】https://app.codegrid.net/entry/2017-mail-address-1
