### ISSUE TITLE
動画検索のUI改善

### ISSUE THREAD

**Issue by kaizumaki** [codeforjapan/StudyAtHome#445]
## 改善詳細 / Details of Improvement
- 時間割作成画面の「（オプション機能）動画検索」の一連のUIがわかりにくいです（スタイリングされていない）。
- この部分のUIをわかりやすくデザインしてほしいです。

## スクリーンショット / Screenshot

- 「検索する」ボタン
![スクリーンショット 2020-10-05 17 44 07](https://user-images.githubusercontent.com/14883063/95559969-867f8700-0a53-11eb-940e-7a9ad3592297.png)
- 検索結果に「参考動画URLに登録する」ボタン
![スクリーンショット 2020-10-05 17 44 38](https://user-images.githubusercontent.com/14883063/95559993-9008ef00-0a53-11eb-8b3d-794e287887ad.png)
- 検索結果は５件ずつのページネーション
![スクリーンショット 2020-10-05 17 44 59](https://user-images.githubusercontent.com/14883063/95560013-97c89380-0a53-11eb-9b07-5733d84691b6.png)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by forestgtree** [comment]
デザイン用意してみましたので、問題なければ実装お願いいたします🙇‍♂️

![search](https://user-images.githubusercontent.com/55567929/95564913-68695500-0a5a-11eb-88eb-7ff74d495982.png)

Figma
https://www.figma.com/file/XFXhMpD7gVxdpyJeEl4srT/covid-edu?node-id=1545%3A0
