### ISSUE TITLE
API 用のfunctionsを用意する

### ISSUE THREAD

**Issue by F88** [codeforjapan/StudyAtHome#59]
## 改善詳細 / Details of Improvement

- 将来のAPI実装の準備としてAPI用のfunctionを追加しておく
  - APIの実装は優先度普通
  - /functions/ 以下のディレクトリ構成等に影響がある為先行して対応しておきたい
    - ディレクトリ構成の変更は必須では無いが変更への耐性を保つ為の対応
- 副作用
  - ssr側で `/api/` というパスを利用出来なくなる
    - これに対する回避策としては ssr の中に /api 相当のルーティングを追加することであるが実装を分割しておいた方が良いと考える為 /api は API用に利用した方が良いと思われる
      - 後述する実装案であれば、Hostingのrewriteにより優先的に functions:api が利用される.

### functions 直下の構成

```
$ tree functions/src/ -L 1
functions/src/
├── api
├── index.ts
└── ssr
```

### functions/src/index.ts

```typescript
// SSR
export * as ssr from './ssr/index'

//API
export * as api from './api/index'
```

### /firebase.json

```json
       "**/node_modules/**"
     ],
     "rewrites": [
+      {
+        "source": "/api",
+        "function": "api"
+      },
       {
         "source": "**",
         "function": "ssr"
```

## スクリーンショット / Screenshot

n/a

## 期待する見せ方・挙動 / Expected behavior

- Cloud Functions for Firebase にAPI用のfunctionが用意される
- Firebase Hosting 側からAPIへのルーティングが可能となる

## 動作環境・ブラウザ / Environment

n/a

**Comment by Nekoya3** [comment]
API周りはすべていったんPending島ｓう

**Comment by F88** [comment]
Pendingについては問題ありません。
将来的なfunction追加に備えてリファクタリングしておければ良いかな程度の案でもあります。

**Comment by F88** [comment]
別途検討した結果を整理しておきます

- APIは専用サブドメインで提供する方向
- 実装は本リポジトリではなく別のリポジトリで行う
  - Firestoreなどを直接参照、現時点では認証は必須では無くGETのみで良さそうである

以上の点から本Issueの提案内容などは全て不要なものとなる為本Issueはcloseしておきます。
