### ISSUE TITLE
編集画面で使用するボタン類の実装

### ISSUE THREAD

**Issue by Nekoya3** [codeforjapan/StudyAtHome#60]
![display-nav](https://user-images.githubusercontent.com/17000370/82720791-d6062600-9cf1-11ea-9f72-fc93519ba0ff.png)
![edit-nav](https://user-images.githubusercontent.com/17000370/82720792-d7375300-9cf1-11ea-8b80-daf8cc128367.png)

ベースとなるボタンをv-btn (Vuetify)を使用して実装をお願いします！

**Comment by MaySoMusician** [comment]
着手します

**Comment by MaySoMusician** [comment]
@Nekoya3 アイコン・ボタン押下時の処理はpropsで渡すか、別途それ用のコンポーネントを作るかどうか？

**Comment by Nekoya3** [comment]
アイコンに関してはpropsで渡していただいて、ボタン押下時の処理は利用側のコンポーネントで@clickなどつかって書くことになるかと思います。
