### ISSUE TITLE
教科名を表示するchipを実装

### ISSUE THREAD

**Issue by Nekoya3** [codeforjapan/StudyAtHome#61]
![subject-tag](https://user-images.githubusercontent.com/17000370/82720843-41e88e80-9cf2-11ea-892b-2a33ea3fd54f.png)

教科名を表示するchipの実装をお願いします。
バックグラウンドの色、中の文字列をpropsで渡せる形でお願いします

v-chipを使用してもOKです

**Comment by osoken** [comment]
着手します
