### ISSUE TITLE
日付を選択するメニューを作成

### ISSUE THREAD

**Issue by Nekoya3** [codeforjapan/StudyAtHome#62]
![image](https://user-images.githubusercontent.com/17000370/82720971-8f193000-9cf3-11ea-9f51-444df448abb5.png)

**Comment by F88** [comment]
着手してみます

**Comment by F88** [comment]
![image](https://user-images.githubusercontent.com/685250/82922638-ce29d880-9fb4-11ea-8a70-fecc7a39c0bb.png)

表示日数は柔軟に変更出来るようにするつもりでしたが、まぁ大丈夫です.

**Comment by F88** [comment]
見た目の対応が終わっていませんが機能的には一通り実装しました。

Usage:

```vue
    <CalendarBar @changeCurrentDate="changeDate" />
    <CalendarBar :view="opts1.view" :config="opts1.config" />
    <CalendarBar :date="opts2.currentDate" :config="opts2.config" />
    <CalendarBar :date="opts3.currentDate" :config="opts3.config" />
```

```typescript
  @Prop({ default: new Date() }) date: Date | undefined
  @Prop({ default: { view: 'Week', startWeekOn: 'Monday' } }) config: CalendarBarConfig | undefined
```

選択された日付は `changeCurrentDate` をemitします。

```typescript
  @Emit('changeCurrentDate')
  changeCurrentDate(): Date {
    return this.dateListWindow.currentDate
  }
```

![image](https://user-images.githubusercontent.com/685250/83345197-5e687480-a34b-11ea-952d-4adcfb7a1273.png)

**Comment by F88** [comment]
なお、ヘッダ方面に日付ピッカーが用意されるようなので、このコンポーネント内部ではピッカーを実装していません。

**Comment by F88** [comment]
表示については大体こんな感じで良さそうなので、一旦これでPR確定します。

- スワイプ時の挙動が寂しい(何もしていない)のでなんとかしたい
は優先度低めになると思うので別Issue扱いとします。

![image](https://user-images.githubusercontent.com/685250/83348195-3ab22800-a365-11ea-97e0-5ed9d65b4fb1.png)
![image](https://user-images.githubusercontent.com/685250/83348206-4b629e00-a365-11ea-815c-a7519092d0c9.png)

![image](https://user-images.githubusercontent.com/685250/83348243-ae543500-a365-11ea-9f8a-38593d693489.png)
