### ISSUE TITLE
クラス設定や、ログアウトを行うために使うボタンを作成

### ISSUE THREAD

**Issue by Nekoya3** [codeforjapan/StudyAtHome#63]
![image](https://user-images.githubusercontent.com/17000370/82720999-f1723080-9cf3-11ea-924e-6b28cbd510e6.png)

中の文字列をpropsで受け渡せる形
v-btnを使用して実装いただけると幸いです

**Comment by Nekoya3** [comment]
v-btnを使うことで解決できそう

**Comment by MaySoMusician** [comment]
もしかしたらわざわざコンポーネントを作らなくても `v-btn` を毎回使えば良いのでは？

**Comment by Nekoya3** [comment]
v-btnつかいましょ
