### ISSUE TITLE
+ボタンを実装

### ISSUE THREAD

**Issue by Nekoya3** [codeforjapan/StudyAtHome#65]
![image](https://user-images.githubusercontent.com/17000370/82721112-5ed29100-9cf5-11ea-9a71-9f722e991e86.png)

#60 とは少しデザインが異なります

**Comment by kota-yata** [comment]
着手します

**Comment by Nekoya3** [comment]
icon: mdi-plus
icon-color (plusの色) : #004170
color: #FFDB6C

**Comment by kota-yata** [comment]
@Nekoya3 
自分の環境構築に問題があり、これ以上作業を進められそうにないのでアサインを外していただけるとありがたいです。申し訳ありません

**Comment by Nekoya3** [comment]
了解しました！お疲れ様でした！

**Comment by F88** [comment]
対応しますのでアサインお願いします

**Comment by F88** [comment]
一旦実装は終わっているのですが、Vue本体のテストケース見ながら唸っているところです...

vuetify/VIcon.spec.ts at 9b77c734523a03261436df056a2d1535a5b67980 · vuetifyjs/vuetify
https://github.com/vuetifyjs/vuetify/blob/9b77c734523a03261436df056a2d1535a5b67980/packages/vuetify/src/components/VIcon/__tests__/VIcon.spec.ts

**Comment by F88** [comment]
![image](https://user-images.githubusercontent.com/685250/82755296-a2202300-9e0d-11ea-8c29-c40cda36bacc.png)

![image](https://user-images.githubusercontent.com/685250/82755308-ac422180-9e0d-11ea-9472-2f9c7c685f2c.png)
