### ISSUE TITLE
何時間目を表示するものの実装

### ISSUE THREAD

**Issue by Nekoya3** [codeforjapan/StudyAtHome#66]
![image](https://user-images.githubusercontent.com/17000370/82721142-93dee380-9cf5-11ea-972a-d76a1f7cd1af.png)

明るい青の背景はつけなくて大丈夫です。
何時間目、何時何分の部分はpropsで受け渡せる形にしてください。

**Comment by F88** [comment]
対応します

**Comment by F88** [comment]
ある程度汎用的につくりましたが、幅広く取った際の 時間表現に改善の余地ありですね :/

![image](https://user-images.githubusercontent.com/685250/82737734-1dca9300-9d6e-11ea-8a8b-a715383e9dc6.png)

![image](https://user-images.githubusercontent.com/685250/82737739-2327dd80-9d6e-11ea-969c-3d8bcd8dcfee.png)

![image](https://user-images.githubusercontent.com/685250/82737742-2622ce00-9d6e-11ea-828a-2717d03197b8.png)
