### ISSUE TITLE
footerを実装する

### ISSUE THREAD

**Issue by Nekoya3** [codeforjapan/StudyAtHome#69]
![image](https://user-images.githubusercontent.com/17000370/82721389-abb76700-9cf7-11ea-88ff-2a7b10c3172f.png)

編集時の身に表示されるメニューです。
#65 の後になると思います。

**Comment by F88** [comment]
実装します

**Comment by Nekoya3** [comment]
ありがとうございます！
可能であれば、このフッターが上に上がって新規登録欄になることを前提として作っていただけると有り難いです

**Comment by F88** [comment]
これがニューッと上がってくるイメージですね、そうなるとコンポーネントの名前を...

![image](https://user-images.githubusercontent.com/685250/83355963-c051ca00-a39d-11ea-9f05-a0d753b49819.png)

**Comment by Nekoya3** [comment]
どうしましょうね………

**Comment by F88** [comment]
`v-bottom-sheet` を使うのが一番手軽なので、とりあえずそれで実装してみました。

Bottom sheet component — Vuetify.js
https://vuetifyjs.com/en/components/bottom-sheets/

![image](https://user-images.githubusercontent.com/685250/83428966-4dfcea80-a46e-11ea-83e6-ccf5ffce8eb8.png)

↑これは複数のシートを使い分ける場合のイメージです。シートの内容を変更することは当然可能なのですが、現時点で判明している問題として、現実装ではスクロールが必要な程の高さになると動作がおかしくなります。

![image](https://user-images.githubusercontent.com/685250/83429191-a633ec80-a46e-11ea-9be5-295e61f1588e.png)

 `scrollable` プロパティを利用すればスクロールさせることは出来るようなのですが、今回実装するコンポーネントに限ってはスクロールするほどのものを想定していないので現時点では一旦簡潔な実装としておきます。以下の実装時にはスクロール必須となるのですが、まずは簡潔な実装としてこのコンポーネントを追加しておきます。

↓ スクロール必須となる機能
![image](https://user-images.githubusercontent.com/685250/83429400-f612b380-a46e-11ea-98e8-d39c7d5cc5f3.png)

**Comment by F88** [comment]
Usage:

```vue
<SimpleSheet :message="message" @addButtonClicked="addX" />
```
```vue
<SimpleSheet :message="message" :expanded="false" @addButtonClicked="addX" />
```

Props:

```typescript
props: {
  message: {
    type: String,
    required: true
  },
  expanded: {
    type: Boolean,
    required: false,
    default: true
  }
}
```

Sample:

![image](https://user-images.githubusercontent.com/685250/83437142-33307300-a47a-11ea-8230-2b79cf4748ed.png)

![image](https://user-images.githubusercontent.com/685250/83437188-43e0e900-a47a-11ea-928b-41ef70405cd2.png)
